//some default colors used in the application

export const theme = { 
    SF_PRO_DISPLAY_BLACK:'SF Pro Display-Black',
    SF_PRO_DISPLAY_BOLD:'SF Pro Display-Bold',
    SF_PRO_DISPLAY_BOLD_ITALIC:'SF Pro Display-BoldItalic',
    SF_PRO_DISPLAY_EXTRA_LIGHT:'SF Pro Display-ExtraLight',
    SF_PRO_DISPLAY_EXTRA_LIGHT_ITALIC:'SF Pro Display-ExtraLightItalic',
    SF_PRO_DISPLAY_ITALIC:'SF Pro Display-Light',
    SF_PRO_DISPLAY_LIGHT:'SF Pro Display-LightItalic',
    SF_PRO_DISPLAY_LIGHT_ITALIC:'SF Pro Display-LightItalic',
    SF_PRO_DISPLAY_REGULAR:'SF Pro Display-Regular',
    SF_PRO_DISPLAY_MEDIUM:'SF Pro Display-Medium',
    SF_PRO_DISPLAY_SEMI_BOLD:'SF Pro Display-SemiBold',
    SF_PRO_DISPLAY_SEMI_BOLD_ITALIC:'SF Pro Display-SemiBoldItalic',
    };
    
    export const colors = {
      TRANSPARENT: 'transparent',
      WHITE: '#FFFFFF',
      WHITE_LOW_OPACITY:'#ffffff3b',
      BLACK: '#000',
      BLACK_LITE:"#000000DE",
      SPLASH_TITLE:'#000000BF',
      BTN_TEXT:'#7B4397',
      ITEM_LABEL_COLOR:"#D2283C",
      YES:'#DBB460',
      LIGHT_GREY:'#DCDCDC',
      NO:'#C1C1C1',
      LABEL:'#707070',
      BR_COLOR:'#DBDBDB',
      PICKER_TEXT_VALUE_COLOR:'#0000008A',
      RESET_BTN:'#000000D6',
      BORDER_COLOR:'#D4D4D4',
      VALUE:'#000000B3',
      DISPOSED:'#FE0404',
      PASS:'#434343',
      REGISTER:'#B43742',
      FORGOT:'#010101',
      COURT_BORDER_COLOR:'#E5E5E5',
      DISCLAIMER:'#404040',
      ORDER_STATUS:'#1B6800',
      BORDER_BOTTOM_COLOR:"#7070708A",
      UNCHECK:"#707070",
      CHECK_BORDER:'#BCBCBC',
      ERROR_BG:'#0000000D',
      ERROR_BORDER:"#0000003D",
      ACCORDION_BG:"#F3F4F4",
      LINK:'#922B72',
      SIDE_BAR_BG:'#713670',
      SIDE_BAR_G_ONE:'#7E2845',
      DASHBOARD_BG_ONE:'#DC2430',
      RADIO_LABEL:"#858585",
      TITLE:"#7B274E",
      LABEL_COLOR:'#484848',
      STATUS_LABEL_COLOR:'#00000089',
      READ_TIME:'#A8B8C1',
      SENDER_COLOR:"#D9E4E9",
      SENDER_MSG:'#50626D',
      SEND_BOX_BORDER:'#D6D6D6',
      EXPEND_VIEW_BG:'#F8F8F8',
      CVV_BORDER:'#C5C5C5',
      LET_OTHER_FIND:'#733266',
      NEW_MESSAGE_HEADING:"#CB2942",
      HEADER:"#343434",
      INPUT_BORDER:"#6580A4",
      TEXTINPUT_BORDER:'#00000042',
      SEARCH_BG:'#8F5C86',
      EMPTY_SLIDER_COLOR:"#CCCCCC4F",
      STREUNG_BTN:"#DA2533",
      EXPIRY:'#F2F2F2',
      SLIDER_HEADING:'#3F2A3D',

      }